spring:
  application:
    name: cryptochat

  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      username: postgres
      password: root
    url: jdbc:postgresql://localhost:5432/cryptochat

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
